<?php
/**
 * Ffuenf_Contact extension.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Ffuenf
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2015 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('ffuenf_contact')->__('Contact Us') ?></h1>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ffuenf_contact')->toHtml(); ?>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="reason"><?php echo Mage::helper('ffuenf_contact')->__('Reason') ?></label>
                    <div class="input-box">
                        <select name="reason" id="reason">
                            <option value=""><?php echo Mage::helper('ffuenf_contact')->__('(choose one)') ?></option>
                            <?php foreach (Mage::helper('ffuenf_contact')->getReasons() as $reason) : ?>
                                <option value="<?php echo $this->htmlEscape($reason) ?>"><?php echo $this->htmlEscape($reason); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('ffuenf_contact')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('ffuenf_contact')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('ffuenf_contact')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('ffuenf_contact')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('ffuenf_contact')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('ffuenf_contact')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('ffuenf_contact')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('ffuenf_contact')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('ffuenf_contact')->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('ffuenf_contact')->__('Message') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('ffuenf_contact')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('ffuenf_contact')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('ffuenf_contact')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>